#!/bin/bash

timeToSleep=1m
blockLines=10

counter=0

function printHelp() {
    echo "-t <sleep time>       Time to sleep between each iteration. Check man sleep for time format."
    echo "-l <line number>      Lines printed in the log before a header printing"
    echo "-h                    Print this helper message"
}

function logProcess() {
    psOutput=$(ps -eo pid,ppid,%mem,%cpu,comm --sort=-%cpu | head -n 2)
    header="DATE $(echo "$psOutput" | sed -n 1p)"
    process="$(date +%m-%d-%Y+%T) $(echo "$psOutput" | sed -n 2p)"
    toPrint=$(echo -e "$header \n $process" | column -t)
    printHeader=$1
    if "$printHeader"
    then
        echo "$toPrint"
    else
        echo "$toPrint" | sed -n 2p
    fi
}

######################## OPTION PARSING ########################

while getopts ":ht:l:" opt; do
	case $opt in
	    h) printHelp ;;
        t) timeToSleep=${OPTARG} ;;
        l) blockLines=${OPTARG} ;;
	    \?) echo "Invalid option -${OPTARG}" ; exit 1;;
	esac
done
shift $((OPTIND-1))



######################## MAIN BODY ########################

while true; do
    if [ $counter -eq 0 ]
    then
        logProcess "true"
    else
        logProcess "false"
        if [ $counter -eq $[$blockLines-1] ]
        then
            echo ""
            counter=-1
        fi
    fi
    counter=$[$counter+1]
    sleep $timeToSleep
done