#!/bin/bash

# Configurable
blockLines=10

counter=0

function logProcess() {
    psOutput=$(ps -eo pid,ppid,%mem,%cpu,args --sort=-%cpu | head -n 2)
    header="DATE $(echo "$psOutput" | sed -n 1p)"
    process="$(date +%m-%d-%Y+%T) $(echo "$psOutput" | sed -n 2p)"
    toPrint=$(echo -e "$header \n $process" | column -t)
    printHeader=$1
    if "$printHeader"
    then
        echo "$toPrint"
    else
        echo "$toPrint" | sed -n 2p
    fi
}

while true; do
    if [ $counter -eq 0 ]
    then
        logProcess "true"
    else
        logProcess "false"
        if [ $counter -eq $[$blockLines-1] ]
        then
            echo ""
            counter=-1
        fi
    fi
    counter=$[$counter+1]
    sleep 1s
done